name: MCP Server CI

on:
  push:
    branches: [ main ]
    paths:
      - 'mcp-server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'mcp-server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mcp-server

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./mcp-server/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript build
      run: npm run build
    
    - name: Run tests
      run: npm test
      env:
        CI: true
        JWT_SECRET: test-secret-for-ci 